plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
    id "org.openapi.generator" version "7.3.0"
}

group = 'com.commercetools'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

repositories {
     mavenCentral()
}

dependencies {

    // ===== Spring Boot =====
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // ===== OpenFeign =====
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation "io.github.openfeign:feign-httpclient:${feignHttpClientVersion}"

    // ===== OpenAPI UI =====
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'

    // ===== Jackson =====
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}"

    // ===== commercetools SDK =====
    implementation "com.commercetools.sdk:commercetools-sdk-java-api:17.6.0"

    // ===== Lombok =====
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // ===== Testing =====
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.1'

    testImplementation 'org.mockito:mockito-core:5.8.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.8.0'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}



dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

openApiGenerate {
    generatorName = "spring"
    library = "spring-boot"
    inputSpec = "$rootDir/src/main/resources/openapi.yaml"
    outputDir = "$buildDir/generated"
    apiPackage = "com.example.commercetoolsDemo.api"
    modelPackage = "com.example.commercetoolsDemo.model"

    configOptions = [
            interfaceOnly        : "true",
            useSpringBoot3       : "true",
            useTags              : "true",
            skipDefaultInterface : "true",
            generateExamples     : "false",
            openApiNullable      : "false"
    ]
}




sourceSets {
    main {
        java {
            srcDir "$buildDir/generated/src/main/java"
        }
    }
}


compileJava.dependsOn tasks.openApiGenerate
