# Add these logging configurations to see the exact JSON being sent

# Enable Feign client logging
logging.level.com.example.commercetoolsDemo.feign.AdminFeignClient=DEBUG

# Enable Spring Web logging
logging.level.org.springframework.web=DEBUG

# Enable your service logging
logging.level.com.example.commercetoolsDemo=DEBUG

# Show request/response bodies
logging.level.org.apache.http=DEBUG



spring.application.name=commercetoolsDemo


server.port=8080

# commercetools project
ct.projectKey=sample_project1

# REGION MUST MATCH POSTMAN (us-east-2)
ct.authUrl=https://auth.us-east-2.aws.commercetools.com/oauth/token
ct.apiUrl=https://api.us-east-2.aws.commercetools.com

# OAuth credentials
ct.clientId=bXd-dfVlIPHrbFgH5lHeUWxb
ct.clientSecret=aqso7zDoo1GAiw4WeQcP28Qd8-Yh9gGF

# Scope MUST use project key
ct.scopes=manage_project:sample_project1
