logging.level.com.example.commercetoolsDemo.feign.AdminFeignClient=DEBUG


logging.level.org.springframework.web=DEBUG

logging.level.com.example.commercetoolsDemo=DEBUG

logging.level.org.apache.http=DEBUG



spring.application.name=commercetoolsDemo


server.port=8080

ct.projectKey=sample_project1


ct.authUrl=https://auth.us-east-2.aws.commercetools.com/oauth/token
ct.apiUrl=https://api.us-east-2.aws.commercetools.com

ct.clientId=vGsElpKBSjLJX3OeJBxiEY8E
ct.clientSecret=yEKtPNrtKvehqvNhpKKsS4drRNjzDAjC

ct.scopes=manage_project:sample_project1
